### PR TITLE
Add unicode support

### PR DESCRIPTION
**Pull request by nikialeksey**
Hello! I have the issue with your docker image:
https://github.com/gradle/gradle/issues/3117

So, can we add unicode support?

### CODE REVIEW

**Comment by jasonfish568** [comment]
This needs to be approved quickly.

**Comment by nikialeksey** [comment]
@txlife You can use workaround: https://hub.docker.com/r/nikialeksey/android-ci/

**Comment by osipxd** [comment]
Please, merge this

**Comment by javiersantos** [comment]
Merged. Thank you!

```yml
image: javiersantos/android-ci:latest
```

**Comment by nikialeksey** [comment]
@javiersantos Thanks!

**Pull request merged**
