### PR TITLE
Apply platforms 28 license

### PR DESCRIPTION
**Pull request by nikialeksey**
To solve this one:
```
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
```

### CODE REVIEW

**Comment by gokulakshay** [comment]
Merge this please..

**Comment by gokulakshay** [comment]
This issue is still there after the merge

**Comment by javiersantos** [comment]
Please, try again using the latest image:

```yml
image: javiersantos/android-ci:latest
```

Docker image takes several minutos to compile.

**Comment by gokulakshay** [comment]
Cool cool, it is working now. I tried after 1 hour and it didn't work. Didn't think it would take that long for Docker image to compile

**Pull request merged**
